name: react frontend auto deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git repository 가져오기
        uses: actions/checkout@v3

      - name: Node.js 설치하기
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 의존성 설치하기
        run: npm install

      - name: 실행파일 빌드하기 (npm run build)
        run: npm run build

      - name: 도커 이미지 빌드하기
        run: docker build -t ${{ secrets.DOCKER_USER }}/react-test:mixed .

      - name: 도커 로그인하기
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: 도커 이미지 푸시하기
        run: docker push ${{ secrets.DOCKER_USER }}/react-test:mixed

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: EC2에 접속해서 Docker 이미지 pull 및 컨테이너 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop react || true
            docker rm react || true
            docker rmi ${{ secrets.DOCKER_USER }}/react-test:mixed || true
            docker pull ${{ secrets.DOCKER_USER }}/react-test:mixed
            docker run -d -p 80:80 --name react ${{ secrets.DOCKER_USER }}/react-test:mixed
